version: '3.1'
services:
  master:
    container_name: master
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      - -master
  worker:
    container_name: worker
    build:
      context: ./
      dockerfile: Dockerfile
