apiVersion: v1
kind: Service
metadata:
  name: distributed-master-service
spec:
  selector:
    workertype: master
    application: likes-distributed
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
    targetPort: 8080
    name: http-server
    
