apiVersion: v1
kind: Service
metadata:
  name: distributed-master-service
  # right now keeping the namespace default then will experiment on it later.
  # namespace: distributed-counter
spec:
  selector:
    workertype: master
    application: likes-distributed
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
    targetPort: 8080
    name: http-server
  - port: 9293
    protocol: TCP
    targetPort: 9293
    name: membership-port
    
  
    
# change the active namespace with kubens!
# brew install kubectx